---
- name: Install unixodbc on MacOSX >= 10.9
  ## Common Erlang/OTP applications e.g. MongooseIM require ODBC.
  ## Building OTP R15B03-1 complains about missing sql.h; more recent OTP releases simply skip the odbc application. See also:
  ## * https://github.com/iriscouch/build-couchdb/issues/94#issuecomment-27160850
  ## * https://coolchevy.org.ua/2014/04/08/kerl-easy-building-and-installing-of-erlangotp-instances/
  homebrew: state=latest name=unixodbc
  when: ansible_distribution == "MacOSX" and ansible_distribution_version | version_compare('10.9', '>=') # and release == "R15B03-1"

- name: Install wxWidgets
  homebrew: state=latest name=wxmac

- name: Build OTP release
  shell: CFLAGS="-I$(brew --prefix)/include" kerl build {{ release }} {{ release }}
